version: "3.9"
services:
  minio:
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: minioroot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
    - "9000:9000"
    - "9001:9001"
    expose:
    - 9000
    - 9001
    volumes:
    - ./minio/data:/data
    command: server /data --console-address "0.0.0.0:9001"
  mlflow:
    build: mlflow
    environment:
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: minioroot
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    ports:
      - "5000:5000"
    expose:
      - 5000
    depends_on:
      - minio
